"""regions — detection must not count PROSE, and stripping must be undoable.

The case that matters most here is `test_comment_mentioning_marker_is_not_a_region`: it is the exact
input that made the first version delete 21% of a healthy file. A substring count treats a header
comment explaining the region rule as a region, and `--strip` then truncates from the comment to EOF.
Every other test in this file is cheap; that one is the reason the file exists.
"""
from __future__ import annotations

import io

from nt8bridge import regions

HEADER = """// MyIndicator.cs
namespace NinjaTrader.NinjaScript.Indicators
{
    public class MyIndicator : Indicator
    {
    }
}
"""

REGION = """
#region NinjaScript generated code
// generated by NinjaTrader — do not edit
public partial class Generated { }
#endregion
"""


def _write(tmp_path, name, text):
    p = tmp_path / name
    io.open(p, "w", encoding="utf-8", newline="").write(text)
    return p


# ── detection ───────────────────────────────────────────────────────────────────────────────────────

def test_no_region_is_not_flagged(tmp_path):
    p = _write(tmp_path, "Clean.cs", HEADER)
    assert regions.count_regions(io.open(p, encoding="utf-8").read()) == 0


def test_one_region_is_healthy(tmp_path):
    text = HEADER + REGION
    assert regions.count_regions(text) == 1


def test_two_regions_are_duplicated(tmp_path):
    text = HEADER + REGION + REGION
    assert regions.count_regions(text) == 2


def test_comment_mentioning_marker_is_not_a_region():
    """A file whose comment explains the rule has ONE region, not two.

    Reported upstream against a healthy file: `count(MARKER)` saw 2, `--strip` cut from the comment
    and deleted 4,838 bytes — 21% of the file — including the legitimate region.
    """
    text = (
        "// This file is edited outside the NinjaScript Editor, so NinjaTrader may append\n"
        "// a second #region NinjaScript generated code block. Strip before compiling.\n"
        + HEADER + REGION
    )
    assert text.count(regions.MARKER) == 2      # what the old code counted
    assert regions.count_regions(text) == 1     # what is actually there


def test_indented_directive_still_counts():
    """C# allows leading whitespace before `#`, so the anchor must permit it."""
    assert regions.count_regions(HEADER + "\n    #region NinjaScript generated code\n#endregion\n") == 1


def test_scan_reports_duplicated_flag(tmp_path):
    (tmp_path / "Indicators").mkdir()
    _write(tmp_path, "Indicators/Healthy.cs", HEADER + REGION)
    _write(tmp_path, "Indicators/Dupe.cs", HEADER + REGION + REGION)
    found = {f["path"].rsplit("\\", 1)[-1].rsplit("/", 1)[-1]: f for f in regions.scan(tmp_path)}
    assert found["Healthy.cs"]["regions"] == 1 and found["Healthy.cs"]["duplicated"] is False
    assert found["Dupe.cs"]["regions"] == 2 and found["Dupe.cs"]["duplicated"] is True


def test_scan_skips_archive(tmp_path):
    (tmp_path / "Indicators" / "_archive").mkdir(parents=True)
    _write(tmp_path, "Indicators/_archive/Frozen.cs", HEADER + REGION + REGION)
    assert regions.scan(tmp_path) == []


# ── stripping ───────────────────────────────────────────────────────────────────────────────────────

def test_strip_removes_the_tail_and_keeps_the_code(tmp_path):
    p = _write(tmp_path, "Dupe.cs", HEADER + REGION + REGION)
    assert regions.strip_file(p) == 2
    out = io.open(p, encoding="utf-8").read()
    assert regions.count_regions(out) == 0
    assert "public class MyIndicator" in out


def test_strip_writes_a_backup(tmp_path):
    original = HEADER + REGION + REGION
    p = _write(tmp_path, "Dupe.cs", original)
    regions.strip_file(p)
    bak = tmp_path / "Dupe.cs.bak"
    assert bak.exists(), "a tool that truncates source must leave an undo"
    assert io.open(bak, encoding="utf-8").read() == original


def test_strip_does_not_touch_a_prose_only_file(tmp_path):
    """No anchored directive ⇒ nothing removed, nothing written, no backup."""
    text = "// mentions #region NinjaScript generated code in prose only\n" + HEADER
    p = _write(tmp_path, "Prose.cs", text)
    assert regions.strip_file(p) == 0
    assert io.open(p, encoding="utf-8").read() == text
    assert not (tmp_path / "Prose.cs.bak").exists()


def test_strip_backup_can_be_disabled(tmp_path):
    p = _write(tmp_path, "Dupe.cs", HEADER + REGION)
    assert regions.strip_file(p, backup=False) == 1
    assert not (tmp_path / "Dupe.cs.bak").exists()
